### ISSUE TITLE
netty-tcnative-boringssl-static-2.0.46 seems failed to work on s390x

### ISSUE THREAD

**Issue by fjfjfan** [linux-on-ibm-z/docs#49]
Dear admins,
Thanks a lot for your guide on how to build netty-tcnative, and I've build netty-tcnative 2.0.46
successfully following https://github.com/linux-on-ibm-z/docs/wiki/Building-netty-tcnative, and copy those two jars 
```
netty-tcnative-boringssl-static-2.0.46.Final-linux-s390_64.jar
netty-tcnative-boringssl-static-2.0.46.Final.jar
```
to work together with `grpc-netty-1.42.0.jar and netty-handler-4.1.72.Final.jar `following
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting

but I got an error as below now:
```
2022-01-12 03:31:45 SEVERE dwa.replication.apply.utilities.TerminatingUncaughtExceptionHandler uncaughtException: Thread MainThread threw an exception. Triggering instance restart.
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:246)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
        at io.grpc.netty.GrpcSslContexts.forServer(GrpcSslContexts.java:105)
        at dwa.replication.apply.management.ManagementServer.<init>(ManagementServer.java:103)
        at dwa.replication.apply.management.Factory.createNewManagementServer(Factory.java:49)
        at dwa.replication.apply.cmd.ManagementServer.<init>(ManagementServer.java:65)
        at dwa.replication.apply.cmd.ManagementServer.main(ManagementServer.java:77)
```

Note:
1. on x86, with the default `netty-tcnative-boringssl-static-2.0.46.Final.jar/grpc-netty-1.42.0.jar/netty-handler-4.1.72.Final.jar`, it works well
2. on s390x, we used `netty-tcnative-boringssl-static-2.0.38.Final.jar/netty-tcnative-boringssl-static-2.0.38.Final-linux-s390_64.jar/grpc-netty-1.42.0.jar/netty-handler-4.1.63.Final.jar`, the netty-tcnative jars were built following your previous guide, and it works well too.

Any suggestions? Thanks a lot!

**Comment by fjfjfan** [comment]
rebuild it on RH 8.4, and also copied netty-tcnative-classes-2.0.46.Final.jar, and it works now.
